/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pos.view;

import java.util.List;
import javax.swing.table.DefaultTableModel;
import pos.dao.ProductDao;
import pos.dao.SalesDao;
import pos.dao.SalesItemDAO;
import pos.model.Sales;
import pos.model.SalesItem;
import pos.util.SalesUtil;

/**
 *
 * @author Admin
 */
public class SalesView extends javax.swing.JFrame {

    ProductDao pd = new ProductDao();
    SalesDao salesDao = new SalesDao();
    SalesUtil salesUtil = new SalesUtil();
    SalesItemDAO salesItemDao = new SalesItemDAO();

    /**
     * Creates new form SalesView
     */
    public SalesView() {
        initComponents();
        loadAllProduct();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        generateSalesTable();
    }

    void generateSalesTable() {
        DefaultTableModel model = new DefaultTableModel();

        String columns[] = {"Product", "Qty", "Unit Price", "Total", "Discount Rate", "Discount", "Actual"};

        model.setColumnIdentifiers(columns);

        tblSalesItem.setModel(model);

    }

    void loadAllProduct() {
        List<String> productNames = pd.getAllProductName();
        comboSalesProduct.removeAllItems();
        comboSalesProduct.addItem("--Select Product--");

        for (String p : productNames) {
            comboSalesProduct.addItem(p);
        }
    }

    void calculateGrandTotal() {

        DefaultTableModel model = (DefaultTableModel) tblSalesItem.getModel();

        double sum = 0;

        for (int i = 0; i < model.getRowCount(); i++) {
            double value = Double.parseDouble(model.getValueAt(i, 6).toString());
            sum += value;
        }

        txtSalesTotalAmount.setText(String.format("%.2f", sum));
    }

    void addItemToTable(SalesItem item) {

        DefaultTableModel model = (DefaultTableModel) tblSalesItem.getModel();

        model.addRow(new Object[]{
            item.getProductName(),
            item.getQuantity(),
            item.getUnitPrice(),
            item.getTotalPrice(),
            item.getDiscountRate(),
            item.getDiscount(),
            item.getActualPrice()
        });
//calculateTotal();
    }

    void clearData() {
        txtSalesActualPrice.setText("");
        txtSalesDiscount.setText("");
        txtSalesDiscountRate.setText("");
        txtSalesID.setText("");
        txtSalesQuantity.setText("");
        txtSalesTotalPrice.setText("");
        txtSalesUnitPrice.setText("");

        loadAllProduct();

    }

    void clearTable() {
        DefaultTableModel model = (DefaultTableModel) tblSalesItem.getModel();
        model.setRowCount(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtSalesID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        comboSalesProduct = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtSalesUnitPrice = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtSalesQuantity = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtSalesTotalPrice = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtSalesDiscountRate = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtSalesDiscount = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtSalesActualPrice = new javax.swing.JTextField();
        btnSales = new javax.swing.JButton();
        btnSalesAddItem = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSalesItem = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        txtSalesTotalAmount = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txtSalesCustomerCell = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtSalesInvoiceNo = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Sales");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        jLabel2.setText("Sales ID");

        txtSalesID.setEditable(false);

        jLabel3.setText("Product");

        comboSalesProduct.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setText("Unit Price");

        jLabel5.setText("Quantity");

        txtSalesQuantity.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSalesQuantityFocusLost(evt);
            }
        });

        jLabel6.setText("Total Price");

        txtSalesTotalPrice.setEditable(false);

        jLabel7.setText("Discount Rate");

        txtSalesDiscountRate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSalesDiscountRateFocusLost(evt);
            }
        });

        jLabel8.setText("Discount");

        txtSalesDiscount.setEditable(false);

        jLabel9.setText("Actual Price");

        txtSalesActualPrice.setEditable(false);

        btnSales.setBackground(new java.awt.Color(255, 102, 102));
        btnSales.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSales.setText("Sales");
        btnSales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalesMouseClicked(evt);
            }
        });

        btnSalesAddItem.setText("Add Item");
        btnSalesAddItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalesAddItemMouseClicked(evt);
            }
        });

        tblSalesItem.setBackground(new java.awt.Color(204, 204, 255));
        tblSalesItem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblSalesItem);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Total Amount");

        txtSalesTotalAmount.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        jLabel10.setText("Customer Cell");

        jLabel12.setText("Invoice No");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtSalesCustomerCell, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSalesInvoiceNo, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(305, 305, 305)
                        .addComponent(jLabel13)))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtSalesCustomerCell, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(txtSalesInvoiceNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(txtSalesID, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(63, 63, 63)
                                .addComponent(jLabel3)
                                .addGap(28, 28, 28)
                                .addComponent(comboSalesProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(63, 63, 63)
                                .addComponent(jLabel4)
                                .addGap(42, 42, 42)
                                .addComponent(txtSalesUnitPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtSalesQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtSalesDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtSalesTotalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel7))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtSalesActualPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtSalesDiscountRate, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnSalesAddItem, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addContainerGap(46, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 716, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtSalesTotalAmount)
                                .addContainerGap())
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(btnSales)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtSalesID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(comboSalesProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtSalesUnitPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtSalesQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtSalesTotalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtSalesDiscountRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtSalesDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txtSalesActualPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalesAddItem))
                .addGap(16, 16, 16)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel11)
                        .addGap(26, 26, 26)
                        .addComponent(txtSalesTotalAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68)
                        .addComponent(btnSales, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtSalesQuantityFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSalesQuantityFocusLost
        // TODO add your handling code here:
        try {
            String qtyText = txtSalesQuantity.getText().trim();
            String priceText = txtSalesUnitPrice.getText().trim();

            if (qtyText.isEmpty() || priceText.isEmpty()) {
                txtSalesTotalPrice.setText("");
                return;
            }

            double quantity = Double.parseDouble(qtyText);
            double unitPrice = Double.parseDouble(priceText);

            double totalPrice = salesUtil.getTotalSalesPrice(unitPrice, quantity);

            txtSalesTotalPrice.setText(String.valueOf(totalPrice));

        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please enter valid numeric values.");
            txtSalesTotalPrice.setText("");
        }
    }//GEN-LAST:event_txtSalesQuantityFocusLost

    private void txtSalesDiscountRateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSalesDiscountRateFocusLost
        // TODO add your handling code here:
        try {
            String qtyText = txtSalesQuantity.getText().trim();
            String priceText = txtSalesUnitPrice.getText().trim();
            String discountRateText = txtSalesDiscountRate.getText().trim();

            if (qtyText.isEmpty() || priceText.isEmpty() || discountRateText.isEmpty()) {
                return;
            }

            double quantity = Double.parseDouble(qtyText);
            double unitPrice = Double.parseDouble(priceText);
            double discountRate = Double.parseDouble(discountRateText);

            double totalPrice = salesUtil.getTotalSalesPrice(unitPrice, quantity);

            double discount = salesUtil.getDiscountAmount(totalPrice, discountRate);
            txtSalesDiscount.setText(String.valueOf(discount));

            double actualPrice = salesUtil.getActualPrice(totalPrice, discount);
            txtSalesActualPrice.setText(String.valueOf(actualPrice));

        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please enter valid numeric values.");
            txtSalesDiscount.setText("");
            txtSalesActualPrice.setText("");
        }

    }//GEN-LAST:event_txtSalesDiscountRateFocusLost

    private void btnSalesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalesMouseClicked
       
        double totalPrice = Double.parseDouble(txtSalesTotalAmount.getText().trim());        
        String customerCell = txtSalesCustomerCell.getText().trim();
        String invoiceNo = "INV-" + txtSalesInvoiceNo.getText().trim();
        Sales sales = new Sales(invoiceNo, customerCell, totalPrice);

        // Save sales and get generated ID
        int salesId = salesDao.save(sales);

        DefaultTableModel model = (DefaultTableModel) tblSalesItem.getModel();

        for (int i = 0; i < model.getRowCount(); i++) {

            String productName = model.getValueAt(i, 0).toString();

            int productId = pd.findIdByName(productName);

            //int productId = Integer.parseInt(model.getValueAt(i, 0).toString());
            double qty = Double.parseDouble(model.getValueAt(i, 1).toString());
            double unitPrice = Double.parseDouble(model.getValueAt(i, 2).toString());
            double total = Double.parseDouble(model.getValueAt(i, 3).toString());
            double discountRate = Double.parseDouble(model.getValueAt(i, 4).toString());
            double discountAmount = Double.parseDouble(model.getValueAt(i, 5).toString());
            double actual = Double.parseDouble(model.getValueAt(i, 6).toString());

            SalesItem item = new SalesItem();
            item.setSalesId(salesId);
            item.setProductId(productId);
            item.setQuantity(qty);
            item.setUnitPrice(unitPrice);
            item.setTotalPrice(total);
            item.setDiscount(discountAmount);
            item.setActualPrice(actual);
            item.setDiscountRate(discountRate);

            salesItemDao.saveSalesItem(item);
        }

        clearData();

        txtSalesCustomerCell.setText("");
        txtSalesInvoiceNo.setText("");
        txtSalesTotalAmount.setText("");
        clearTable();

    }//GEN-LAST:event_btnSalesMouseClicked

    private void btnSalesAddItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalesAddItemMouseClicked
        // TODO add your handling code here:
        ProductDao dao = new ProductDao();
        int productId = dao.findIdByName(comboSalesProduct.getSelectedItem().toString());
        String productName = comboSalesProduct.getSelectedItem().toString();

        DefaultTableModel model = (DefaultTableModel) tblSalesItem.getModel();

        double qty = Double.parseDouble(txtSalesQuantity.getText());
        double price = Double.parseDouble(txtSalesUnitPrice.getText());
        double discountRate = Double.parseDouble(txtSalesDiscountRate.getText());
        double totalPrice = Double.parseDouble(txtSalesTotalPrice.getText());
        double discountAmount = Double.parseDouble(txtSalesDiscount.getText());
        double actualPrice = Double.parseDouble(txtSalesActualPrice.getText());

        SalesItem item = new SalesItem();
        item.setProductName(productName);
        item.setQuantity(qty);
        item.setUnitPrice(price);
        item.setDiscountRate(discountRate);
        item.setTotalPrice(totalPrice);
        item.setDiscount(discountAmount);
        item.setActualPrice(actualPrice);

        //item.calculatePrice(); // method from SalesItem to set totalPrice, discount, actualPrice
        addItemToTable(item);
        calculateGrandTotal();
        clearData();

    }//GEN-LAST:event_btnSalesAddItemMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SalesView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SalesView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SalesView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SalesView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SalesView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSales;
    private javax.swing.JButton btnSalesAddItem;
    private javax.swing.JComboBox<String> comboSalesProduct;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblSalesItem;
    private javax.swing.JTextField txtSalesActualPrice;
    private javax.swing.JTextField txtSalesCustomerCell;
    private javax.swing.JTextField txtSalesDiscount;
    private javax.swing.JTextField txtSalesDiscountRate;
    private javax.swing.JTextField txtSalesID;
    private javax.swing.JTextField txtSalesInvoiceNo;
    private javax.swing.JTextField txtSalesQuantity;
    private javax.swing.JTextField txtSalesTotalAmount;
    private javax.swing.JTextField txtSalesTotalPrice;
    private javax.swing.JTextField txtSalesUnitPrice;
    // End of variables declaration//GEN-END:variables
}
